FLUME-512: Must rethrow Throwables in RollSink - some throwables such as NoClassDefFoundError are Errors which are not exceptions and would inadvertently get swallowed.
From: Jonathan Hsieh <jon@cloudera.com>

git-svn-id: https://svn.apache.org/repos/asf/incubator/flume/trunk@1155949 13f79535-47bb-0310-9956-ffa450edef68