FLUME-3142: Fixed configuration class for HBase2.
It was HBase2Sink due to copy-paste error which led to NoSuchMethodError.
Defining a non-existing class (like in case of HBase and many other sinks) won't cause error and the default SinkConfiguration will be initialized.